### ISSUE TITLE
Have you had any problem in the sense that... they steal your login identification? I would like certification that it is not a malicious app. I haven't had any problems, but I got this morning that someone had tried to log into my Riot account, I want to verify that the owner of the app does not have malicious purposes

### ISSUE THREAD

**Issue by Terevenen2** [Terevenen2/LOL-Client-TOOL#5]
Have you had any problem in the sense that... they steal your login identification? I would like certification that it is not a malicious app. I haven't had any problems, but I got this morning that someone had tried to log into my Riot account, I want to verify that the owner of the app does not have malicious purposes

_Originally posted by @Th3Nigh7mare in https://github.com/Terevenen2/LOL-Client-TOOL/issues/4#issuecomment-1192451218_

**Comment by Terevenen2** [comment]
Hi @Th3Nigh7mare I can tell you the app doesn't do this kind of things, the only information that the app saves is on the computer and located in "C:\Users\%username%\AppData\Local\LOL_Client_TOOL" and there is no sensitive information stored for now.
If someone has the time to review the shit show that is my code to testify that I don't lie it would be nice.

**Comment by sakula6** [comment]
After I checked the code, everything was normal. Is there any possibility of ID leakage
