### ISSUE TITLE
Stop working on new version

### ISSUE THREAD

**Issue by LeonardoFBR** [Terevenen2/LOL-Client-TOOL#6]

**Comment by Terevenen2** [comment]
Ok, so the WMIC part stopped working for some reasons and the Process.waitForExit() exit never appended which prevented the fallback on the lock file read.
I removed WMIC part and as of today the tool will only rely on the lock file to connect to the LCU API it could be linked to Windows 11 dropping WMIC but I don't have the time to investigate further for now
I updated the 0.20 with a working version, here a link to the pre-release : https://github.com/Terevenen2/LOL-Client-TOOL/releases/tag/0.20
