### ISSUE TITLE
The UI on my computer doesn't show off

### ISSUE THREAD

**Issue by GeorgesT08** [Terevenen2/LOL-Client-TOOL#7]
Hello, 
I downloaded the 0.22 version of the LOL client TOOL and extracted it and after, executed the .exe file.
A window appears, the some checkboxes and other stuff too, but no informations. 
Did someone had the same issue as i do ? [](url)
GeorgesT08

**Comment by Terevenen2** [comment]
Hello, is the client started ?

**Comment by GeorgesT08** [comment]
the league client ?

**Comment by Terevenen2** [comment]
yes

**Comment by GeorgesT08** [comment]
it wasn't  i'll try to run my game client then the tool

**Comment by GeorgesT08** [comment]
Thanks for your help, i didn't thought one second about opening the league client first .
It worked !
Thanks for your support and your reactivity.
Best Regards

**Comment by Terevenen2** [comment]
No problem
Always happy to help
Have a nice day
